name: Build

on:
  push:
    branches:
      - master
  
jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone this repo
      uses: actions/checkout@v2
      
    - name: Setup node.js environment
      uses: actions/setup-node@v2
      
    - name: Install dependencies
      run: npm ci
      
    - name: Lint with TSLint
      run: npm run lint

    - name: Copy example config
      run: cp config.example.json config.json
      
    - name: Build
      run: npm run build
      
    - name: Upload built app
      uses: actions/upload-artifact@v2
      with:
        name: subathon_timer
        path: dist/
      
